---
plugin: aws_ec2
regions:
  - "{{ lookup('env', 'AWS_REGION') | default('us-east-1', true) }}"
filters:
  tag:Project: workbench-remote
  instance-state-name:
    - running
keyed_groups:
  - prefix: owner
    key: tags.Owner
hostnames:
  - tag:Name
compose:
  ansible_host: instance_id
strict_permissions: false
