---
- name: Install mpm-cli via pipx
  ansible.builtin.shell:
    cmd: pipx install mpm-cli
    creates: "/home/{{ linux_user }}/.local/bin/mpm"
  become: true
  become_user: "{{ linux_user }}"
  environment:
    PIPX_HOME: "/home/{{ linux_user }}/.local/pipx"
    PIPX_BIN_DIR: "/home/{{ linux_user }}/.local/bin"
